In [1]:
import pandas as pd
import numpy as np

superstore = pd.read_csv(
    "../data/processed/superstore_clean.csv",
    encoding="latin1"
)

products = (
    superstore[
        ["Product ID", "Product Name"]
    ]
    .drop_duplicates()
)

np.random.seed(42)

inventory = pd.DataFrame()

inventory["product_id"] = products["Product ID"]

inventory["current_stock"] = np.random.randint(
    50,
    1000,
    len(products)
)

inventory["reorder_level"] = np.random.randint(
    20,
    200,
    len(products)
)

inventory["supplier_lead_time"] = np.random.randint(
    2,
    30,
    len(products)
)

inventory.to_csv(
    "../data/external/inventory_data.csv",
    index=False
)

inventory.head()

        product_id  current_stock  reorder_level  supplier_lead_time
0  FUR-BO-10001798            152            101                  10
1  FUR-CH-10000454            485            135                  26
2  OFF-LA-10000240            910            186                   8
3  FUR-TA-10000577            320            165                  29
4  OFF-ST-10000760            156            122                   4

In [2]:
import pandas as pd
import numpy as np

superstore = pd.read_csv(
    "../data/processed/superstore_clean.csv",
    encoding="latin1"
)

products = (
    superstore[
        ["Product ID", "Product Name", "Sales"]
    ]
    .groupby(
        ["Product ID", "Product Name"]
    )
    .mean()
    .reset_index()
)

np.random.seed(42)

competitors = pd.DataFrame()

competitors["product_id"] = products["Product ID"]

competitors["competitor_name"] = np.random.choice(
    [
        "Amazon",
        "Walmart",
        "Target",
        "BestBuy"
    ],
    len(products)
)

competitors["our_price"] = (
    products["Sales"]
    .round(2)
)

competitors["competitor_price"] = (
    competitors["our_price"] *
    np.random.uniform(
        0.9,
        1.1,
        len(products)
    )
).round(2)

competitors["capture_date"] = pd.Timestamp.today().date()

competitors.to_csv(
    "../data/external/competitor_data.csv",
    index=False
)

competitors.head()

        product_id competitor_name  our_price  competitor_price capture_date
0  FUR-BO-10000112          Target     825.17            891.19   2026-06-07
1  FUR-BO-10000330         BestBuy     354.87            381.41   2026-06-07
2  FUR-BO-10000362          Amazon     430.87            439.26   2026-06-07
3  FUR-BO-10000468          Target     120.64            123.07   2026-06-07
4  FUR-BO-10000711          Target     425.88            439.94   2026-06-07